apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
namespace: default
images:
- name: backend
  newName: 978251544392.dkr.ecr.us-east-1.amazonaws.com/backend
  newTag: toantd19
