name: Trivy Demo Pass

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

jobs:
  lint-backend:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-backend-lint
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: cd starter/backend && pipenv install --dev

      - name: Lint code
        run: cd starter/backend && pipenv run lint

  test-backend:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-backend-test
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: cd starter/backend && pipenv install

      - name: Run tests
        run: cd starter/backend && pipenv run test

  backend-deploy:
    needs: [ lint-backend, test-backend ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ARN_Role }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.9.4'  # specify the Helm version you want to use

      - name: Build, tag image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BE_REPO_NAME }}
          IMAGE_TAG: toantd19
        run: |
          cd starter/backend
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.run_number }}" .
          ###docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      
      - name: Run Trivy vulnerability scanner (Table output)
        uses: aquasecurity/trivy-action@0.20.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BE_REPO_NAME }}
        with:
          image-ref: '${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BE_REPO_NAME }}
        with:
          image-ref: '${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}'
          format: 'json'
          output: 'trivy-report.json'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Check for critical and high vulnerabilities
        id: check-vulnerabilities
        run: |
          # Parse JSON and extract vulnerabilities with CRITICAL or HIGH severity
          cat trivy-report.json
          CRITICAL_COUNT=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' trivy-report.json || echo "0")
          HIGH_COUNT=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH")] | length' trivy-report.json || echo "0")
          echo "Critical vulnerabilities: $CRITICAL_COUNT"
          echo "High vulnerabilities: $HIGH_COUNT"
          echo "::set-output name=critical_count::$CRITICAL_COUNT"
          echo "::set-output name=high_count::$HIGH_COUNT"

      - name: Send alert to Microsoft Teams if vulnerabilities found
        if: steps.check-vulnerabilities.outputs.critical_count != '0' || steps.check-vulnerabilities.outputs.high_count != '0'
        env:
          WEBHOOK_URL: ${{ secrets.Teams_Hook }}
          CRITICAL_COUNT: ${{ steps.check-vulnerabilities.outputs.critical_count }}
          HIGH_COUNT: ${{ steps.check-vulnerabilities.outputs.high_count }}
        run: |
          # Replace the following URL with your Teams webhook URL
          curl -H 'Content-Type: application/json' -d '{
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "summary": "Trivy Scan Report",
            "themeColor": "FF0000",
            "sections": [{
              "activityTitle": "Trivy Vulnerability Scan",
              "activitySubtitle": "Critical and High severity vulnerabilities found",
              "facts": [{
                "name": "Critical vulnerabilities",
                "value": "'$CRITICAL_COUNT'"
              },{
                "name": "High vulnerabilities",
                "value": "'$HIGH_COUNT'"
              }],
              "markdown": true
            }]
          }' $WEBHOOK_URL
      - name: Build, tag image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BE_REPO_NAME }}
          IMAGE_TAG: toantd19
        run: |
          cd starter/backend
          docker pull 730335291032.dkr.ecr.us-east-1.amazonaws.com/backend:9
          ###docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      
      - name: Run Trivy vulnerability scanner (Table output)
        uses: aquasecurity/trivy-action@0.20.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BE_REPO_NAME }}
        with:
          image-ref: 730335291032.dkr.ecr.us-east-1.amazonaws.com/backend:9
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Fail build if critical or high vulnerabilities found
        if: steps.check-vulnerabilities.outputs.critical_count != '0' || steps.check-vulnerabilities.outputs.high_count != '0'
        run: exit 1		

      - name: push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BE_REPO_NAME }}
          IMAGE_TAG: toantd19
        run: |
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
